document.getElementById('lookupBtn').addEventListener('click', lookup);

function lookup(){
  const q = document.getElementById('termInput').value.trim();
  const results = document.getElementById('results');
  results.innerHTML = '';
  if(!q){
    results.innerHTML = '<li class="empty">Please enter a term.</li>';
    return;
  }
  const mock = {
    "bet": {def: "agreement, sure", examples:["Wanna go to the movies? Bet!"]},
    "ghosted": {def: "suddenly stop communicating", examples:["I got ghosted after the second date."]},
    "bro": {def: "brother, friend", examples:["Bro, wanna hang out later?"]},
    "ts": {def: "this shit, this", examples:["Ts is crazy!"]},
    "pmo": {def: "pisses me off", examples:["School really pmo."]},
    "mid": {def: "not good", examples:["The group project is mid."]},
    "ngl": {def: "not gonna lie", examples:["Ngl I would have done the same."]},
    "asl": {def: "as hell", examples:["He's cute asl"]},
    "iykyk": {def: "if you know you know", examples:["the office season 7, episode 19, minute 14:45, iykyk!"]},
    "wdym": {def: "what do you mean", examples:["Wdym bro."]},
    "wdyw": {def: "what do you want", examples:["Bro wdyw."]},
    "tuff": {def: "cool, impressive, awesome, or admirable", examples:["That's not tuff bro."]},
    "edging": {def: "masturbating", examples:["People are trying to stop edging"]},
    "goat": {def: "greatest of all time", examples:["Bro you're the goat."]},
    "cap": {def: "lie", examples:["Stop the cap."]},
    "extra": {def: "dramatic, attention-grabbing, too much.", examples:["Don't be that extra"]},
    "grwm": {def: "get ready with me", examples:["I'm going to watch Barcelona's football match grwm!"]},
    "spill the tea": {def: "tell a secret", examples:["What have you been doing? Spill the tea!"]},
    "sybau": {def: "shut your bitch ass up", examples:["Bro sybau i'm trying to do school work."]},
    "insane": {def: "more than incredible", examples:["Wow! The group project is insane!"]},
    "bussin": {def: "very good", examples:["This chips are bussin!"]},
    "bussin'": {def: "very good", examples:["This chips are bussin!"]},
    "idk": {def: "i don't know", examples:["I bought this, idk why."]},
    "ik": {def: "i know", examples:["Ik, ik, stop telling me what to do."]},
    "yap": {def: "talk in an annoying way", examples:["Stop yapping im trying to focus."]},
    "bruh": {def: "even moremodern way of bro", examples:["This chips are bussin!"]},
    "cringe": {def: "embarassing", examples:["Bro you're so cringe."]},
    "drip": {def: "cool style or trending outfit", examples:["Bro you have drip on today."]},
    "fomo": {def: "fear of missing out", examples:["The fomo hitting again."]},
    "lit": {def: "amazing, exciting or fun", examples:["This party is lit!"]},
    "vibe": {def: "the atmosphere or feeling of a place/person.", examples:["The cafe has a chill vibe."]},
    "chill": {def: "relaxed, calm, or easygoing", examples:["I'm just gonna chill at home tonight."]},
    "adulting": {def: "doing something that adults do", examples:["Adulting is not fun at all."]},
    "bestie": {def: "best friend", examples:["You are my bestie!"]},
    "boi": {def: "another way of saying boy", examples:["The bois and I are going to hang out."]},
    "bop": {def: "very good song", examples:["This new song is a bop!"]},
    "boutta": {def: "about to", examples:["I'm boutta do something evil 😈."]},
    "yeet": {def: "to throw something with force", examples:["He yeeted the ball across the field."]},
    "salty": {def: "being upset or bitter", examples:["She was salty about losing the game."]},
    "brainrot": {def: "effortless, slop content", examples:["Brainrot is so bad."]},
    "brain rot": {def: "effortless, slop content", examples:["Brainrot is so bad."]},
    "flex": {def: "to show off", examples:["He's always flexing his new gadgets."]},
    "flexing": {def: "to show off", examples:["Stop flexing your wealth."]},
    "savage": {def: "brutally honest, fierce, unapologetically bold, or impressively cool", examples:["That comeback was savage!"]},
    "glow up": {def: "a significant transformation in appearance, style, or overall demeanor", examples:["She had a major glow up over the summer."]},
    "glowup": {def: "a significant transformation in appearance, style, or overall demeanor", examples:["She had a major glow up over the summer."]},
    "glaze": {def: "to look at someone with admiration or desire", examples:["He couldn't help but glaze at her beauty."]},
    "glazing": {def: "to look at someone with admiration or desire", examples:["Stop glazing like that."]},
    "meatrider": {def: "being obsessed with someone or... something", examples:["He's a meatrider."]},
    "meat rider": {def: "being obsessed with someone or... something", examples:["He's a meatrider."]},
    "simp": {def: "someone who does way too much for a person they like", examples:["He's such a simp for her."]},
    "gyatt": {def: "a big butt", examples:["Damn, she got a nice gyatt!"]},
    "damn": {def: "expression of surprise or admiration", examples:["Damn, that was an amazing performance!"]},
    "fr": {def: "for real", examples:["I'm tired of this fr."]},
    "slaps": {def: "something that is really good", examples:["This song slaps!"]},
    "goes hard": {def: "something that is really good", examples:["This song goes hard!"]},
    "slay": {def: "to do something exceptionally well", examples:["She slays every time she performs."]},
    "canon": {def: "something that is officially part of a story", examples:["In the Harry Potter canon, wizards can fly on broomsticks."]},
    "canon event": {def: "an event that are officially part of a story", examples:["This website is a canon event of my life. (thank you alot ❤️)"]},
    "ceo of": {def: "incredibly good at something", examples:["She's the CEO of cooking delicious meals."]},
    "clout": {def: "influence or power, especially in social media", examples:["He has a lot of clout on Instagram."]},
    "cooked": {def: "destroyed or defeated in a metaforical way", examples:["You got cooked."]},
    "deadass": {def: "seriously or genuinely", examples:["I'm deadass about this."]},
    "dead ass": {def: "seriously or genuinely", examples:["I'm deadass about this."]},
    "dead": {def: "expression of laughter or amusement", examples:["I was dead when I saw that meme."]},
    "dying": {def: "expression of laughter or amusement", examples:["I'm dying at this joke."]},
    "delulu": {def: "someone who is delusional or unrealistic", examples:["She's a delulu about her future career."]},
    "f" : {def: "showing the utmost respect", examples:["I fell on the floor, F."]},
    "facts": {def: "used to agree with something", examples:["-That movie was amazing. -facts!"]},
    "fire": {def: "something that is really good", examples:["This song is fire!"]},
    "fit": {def: "short for outfit", examples:["Your fit is on point today!"]},
    "gas": {def: "to hype someone up or give them compliments", examples:["Stop gassing me up bro."]},
    "gassing": {def: "to hype someone up or give them compliments", examples:["Stop gassing me up bro."]},
    "lowkey": {def: "to keep something discreet or secretive", examples:["I lowkey like that song."]},
    "low key": {def: "to keep something discreet or secretive", examples:["I lowkey like that song."]},
    "highkey": {def: "to openly express something", examples:["I highkey love that movie."]},
    "high key": {def: "to openly express something", examples:["I highkey love that movie."]},
    "mood": {def: "a relatable feeling or vibe", examples:["That meme is such a mood."]},
    "gucci": {def: "good, cool, or going well", examples:["Everything's gucci!"]},
    "sus": {def: "suspicious or untrustworthy", examples:["That story sounds sus."]},
    "shitpost": {def: "a post that is intentionally absurd or low-quality", examples:["This meme is a total shitpost."]},
    "stan": {def: "an extremely devoted fan", examples:["I'm a huge stan of that band."]},
    "shook": {def: "surprised or shocked", examples:["I was shook when I heard the news."]},
    "thirsty": {def: "desperate for attention or approval", examples:["He's so thirsty for likes on his posts."]},
    "woke": {def: "being aware and informed", examples:["She's really woke about social issues."]},
    "yeeted": {def: "thrown with force", examples:["He yeeted the ball across the field."]},
    "iykwim": {def: "if you know what i mean", examples:["That movie was really intense, iykwim."]},
    "irl": {def: "in real life", examples:["We should hang out irl sometime."]},
    "dm": {def: "direct message", examples:["I'll send you a dm later."]},
    "keep it 100": {def: "to be honest or truthful", examples:["I always keep it 100 with my friends."]},
    "bread": {def: "money", examples:["I'm trying to make some bread this month."]},
    "cheese": {def: "money", examples:["He's all about that cheese."]},
    "ohio": {def: "strange, weird", examples:["Only in Ohio.(to be clear, me, the developer has nothing against the State Of Ohio)"]},
    "op": {def: "overpowered", examples:["That character is so op!"]},
    "poggers": {def: "expression of excitement or amazement", examples:["Poggers! That was an incredible play!"]},
    "rizz": {def: "charisma or charm", examples:["He's got rizz for days."]},
    "pog": {def: "expression of excitement or amazement", examples:["Pog! That was an incredible play!"]},
    "pov": {def: "point of view", examples:["The movie is shot from the pov of the main character."]},
    "rip": {def: "rest in peace", examples:["RIP to my favorite show that got canceled."]},
    "rent free": {def: "constantly on someone's mind", examples:["That catchy song is living rent free in my head."]},
    "rn": {def: "right now", examples:["I'm busy rn, can we talk later?"]},
    "say less": {def: "i understand, no need to explain further", examples:["You want to grab food? Say less, I'm starving."]},
    "sigma": {def: "independent MALE and self-reliant person", examples:["He's a sigma who prefers to work alone."]},
    "sis": {def: "short for sister", examples:["Hey sis, how's it going?"]},
    "smh": {def: "shaking my head", examples:["Smh, I can't believe he did that."]},
    "smt": {def: "something", examples:["I have smt to tell you later."]},
    "smol": {def: "small", examples:["Look at that smol puppy!"]},
    "snack": {def: "an attractive person", examples:["He's such a snack!"]},
    "l": {def: "loss or defeat", examples:["We took an L in that game."]},
    "take the L": {def: "accept a loss or defeat", examples:["Sometimes you just have to take the L and move on."]},
    "thicc": {def: "having a full-figured body", examples:["That character in the game is thicc!"]},
    "whip": {def: "car", examples:["Check out my new whip!"]},
    "w": {def: "win or victory", examples:["We got the W in that match!"]},
    "v": {def: "very", examples:["That movie was v good!"]},
    "af": {def: "as fuck", examples:["That movie was good af!"]},
    "dick": {def: "rude and bad way of representing masculine intimate part", examples:["The dick is important for reproduction."]},
    "dickhead": {def: "a person who is an asshole", examples:["He's such a dickhead!"]},
    "dick head": {def: "a person who is an asshole", examples:["He's such a dick head!"]},
    "dih": {def: "rude and bad way of representing masculine intimate part", examples:["The ih is important for reproduction."]},
    "bedrot": {def: "staying in bed for a long amount of time", examples:["I'm just going to bedrot all day today."]},
    "cancel": {def: "to collectively withdraw support from someone or something", examples:["MR.Beast got canceled"]},
    "caught in 4k": {def: "caught doing something with proof", examples:["He was caught in 4k."]},
    "clapback": {def: "a response to criticism or insult", examples:["She gave him a good clapback."]},
    "karen": {def: "a woman who makes a scene publicly (for a male : daren)", examples:["She's such a karen!"]},
    "touch grass": {def: "to go outside and experience real life", examples:["You should touch grass more often. (like me making this 😒)"]},
    "kms": {def: "kill myself", examples:["I'm so tired, I might kms.(⚠️ DON'T!)"]},
    "kys": {def: "kill yourself", examples:["YOU KNOW WHAT? Kys!(⚠️ DON'T!)"]},
    "NSFW": {def: "not safe for work", examples:["That video is NSFW."]},
    "SFW": {def: "safe for work", examples:["This content is SFW."]},
    "SFWAF": {def: "safe for work and family", examples:["This content is SFWAF."]},
    "Stinks": {def: "something that smells bad", examples:["That trash can stinks."]},
    "Stink": {def: "something that smells bad", examples:["That trash can stinks."]},
    "aced": {def: "get a perfect score", examples:["I aced a test."]},
    "ace": {def: "get a perfect score", examples:["I ace a test."]},
    "asap": {def: "as fast as possible", examples:["Please respond asap."]},
    "ass": {def: "rude way to say butt", examples:["The ass is a part of the body."]},
    "lol": {def: "laugh out loud", examples:["That was so funny, lol."]}
  };

  const item = mock[q.toLowerCase()];
  if(!item){
    results.innerHTML = `<li>No entry found for <strong>${escapeHtml(q)}</strong>. check it's spelling, change it's tense or contact if it's right.</li>`;
    return;
  }

  const li = document.createElement('li');
  li.innerHTML = `<strong>${escapeHtml(q)}</strong> — ${escapeHtml(item.def)}<br><em>Examples:</em><ul>${item.examples.map(e => `<li>${escapeHtml(e)}</li>`).join('')}</ul>`;
  results.appendChild(li);
}

function escapeHtml(s){return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
